### ISSUE TITLE
Incomplete post, maybe?

### ISSUE THREAD

**Issue by saibotsivad** [TehShrike/joshduff.com#2]
I was reading your blog and noticed [this one](https://github.com/TehShrike/joshduff.com/blob/master/content/2010-08-23-on-growing-as-a-programmer-i-think.md), where you wrote only two short paragraphs.

I was wondering if you could maybe expound a bit more on how you have grown as a programmer. Not so much things like "I use these exact tools" or "I read these specific books" (although that would be cool too), but more like "I resolved to read for 8 hours a day" or like "I unclutter my news feeds using these 7 weird tricks".

Anyway, I'd like to know how you've gotten better at what you do!

**Comment by TehShrike** [comment]
I deleted that post in my latest purge of posts-I-no-longer-consider-profitable-enough-to-host-on-my-professional-site :joy: 

I am considering a series on my growth as an application developer though!
