### ISSUE TITLE
Review of "why you need a state router"

### ISSUE THREAD

**Issue by saibotsivad** [TehShrike/joshduff.com#3]
It took me several reads to understand bullet point 1. Maybe something along the lines of:

```diff
- they see whatever the default/first submenu is. This is bad because you
+ they see whatever the default state is for that route, instead of the one they were on. This means you
```

---

> you can't link to the settings page without having to link to one of its sub-pages

Just a note that, if you have `/app/settings/profile` and `/app/settings/account` the URL might then imply that `/app/settings` is a valid route, although you might not want it to be. Might be worth mentioning somewhere, related to the `abstract: true` of Angular.

---

Other than that, it was pretty good!

**Comment by TehShrike** [comment]
Very related, at this moment /app/settings would appear to be a valid url - see https://github.com/TehShrike/abstract-state-router/issues/33
