### ISSUE TITLE
You should write about the word "liberal"

### ISSUE THREAD

**Issue by saibotsivad** [TehShrike/joshduff.com#8]
You keep talking about how we shouldn't use the word "liberal", but I would like you to write your thoughts out more completely.

Alternately/Also, you could link to a handful of articles that you think would help an intelligent person think more betterly about the topic.

**Comment by TehShrike** [comment]
I think I'll be keeping the post more professionally-focused going forward, but it would be nice if I could write a few coherent paragraphs on tribal language at some point.
